// <auto-generated />
namespace Web_Api___Ventas_Online_MP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Nicknames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nicknames));
        
        string IMigrationMetadata.Id
        {
            get { return "201504120614130_Nicknames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
